---

node_config_directory: "/etc/ovn-scale-test"
ontainer_config_directory: "/var/lib/ovn-scale-test/config_files"

###################
# Docker options
###################

#ovn_db_image: "huikang/ovn-scale-test-ovn-local-master-debug"
ovn_db_image: "huikang/ovn-scale-test-ovn-local-master-profiling"
ovn_chassis_image: "huikang/ovn-scale-test-ovn-local-master"

rally_image: "huikang/ovn-scale-test-rally-local-master"


###################
# Emulation options
###################

ovn_database_alias_ip: "172.16.100.3/16"
ovn_database_device: "eth0.3239"

ovn_chassis_start_cidr: "172.16.100.10/16"
ovn_chassis_device: "eth0.3239"

# Total number of emulated chassis
ovn_number_chassis: 2

# pin container to cores, e.g., "29,30,31"
north_db_cpu_set: "29"
south_db_cpu_set: "30"
northd_cpu_set: "31"

########################
# Rally workload options
########################
network_start_cidr: "192.168.100.0/16"
network_number: "1"
ports_per_network: "200"

########################
# OVS Repository to test
########################
ovs_repo: "https://github.com/openvswitch/ovs.git"
ovs_branch: "master"

###################
# Profiling options
###################
enable_oprofile: "yes"
